name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.12.3'
        otp-version: '24.1'
    - name: Install Dependencies
      run: mix deps.get
    - name: Download shape data
      run: mix tz_world.update
    - name: Run Tests
      run: mix test
