name: Release

on:
   release:
     types:
       - created

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.12.3'
        otp-version: '24.1'
    - name: Install Dependencies
      run: mix deps.get
    - name: Download and process shape data
      run: mix tz_world.update
    - name: Upload Geodata to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./priv/timezones-geodata.etf.zip
        asset_name: timezones-geodata.etf.zip
        asset_content_type: binary/octet-stream
       
       